# Generated by Django 3.2.9 on 2021-11-27 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LegacyModel',
        ),
    ]
